Wait transaction confirmation
dusk-network/xsc-governance pull request #10
Opened 2023-03-07 16:25 UTC by herr-seppia

### governance-core
- Change `send_data` to wait for tx confirmation
- Fix `ChangeType::Cash` to use `SecurityDefinition::Cash` contract
- Add `info!` while sending data
 
### governance-cli
- Add `tracing-subscriber`
- Add `graphql_address` to example config

Resolves #9

2023-03-07 16:49 UTC, Daksh14 requested changes

2023-03-07 16:49 UTC, Daksh14 commented on governance-core/src/gql.rs
> +    status: fn(&str),
Is there a particular reason we are using a function pointer instead of a `T: Fn` which is less restrictive?

2023-03-07 16:49 UTC, Daksh14 commented on governance-core/src/gql.rs
> +}
newline between struct declerations

2023-03-07 16:55 UTC, herr-seppia commented on governance-core/src/gql.rs
> +    status: fn(&str),
It's to keep it consistent with the `connect_with_status` already used

2023-03-08 12:32 UTC, herr-seppia commented on governance-core/src/gql.rs
> +    status: fn(&str),
nvm, changed

2023-03-10 08:42 UTC, Daksh14 requested changes

2023-03-10 08:42 UTC, Daksh14 commented on governance-core/src/lib.rs
> +mod gql;
Are we sure this doesn't need to be pub? If it needs to be accessed in the cli, it needs to be pub

2023-03-10 08:42 UTC, Daksh14 commented on governance-core/src/lib.rs
> +                let tx_id = format!("{:x}", tx_hash);
Pass the hash to the wait_for method and put the format there. Makes this code readable. Can you also add a comment to explain the `{:x}`?

2023-03-10 08:51 UTC, herr-seppia commented on governance-core/src/lib.rs
> +mod gql;
it's not accessed by the cli

2023-03-10 08:55 UTC, herr-seppia commented on governance-core/src/lib.rs
> +                let tx_id = format!("{:x}", tx_hash);
The wait method require the tx_id in form of String, I would like to avoid to mess it up with `Scalar`

About the `{:x}` is a [standard formatter](https://doc.rust-lang.org/std/fmt/trait.LowerHex.html)

2023-03-10 09:02 UTC, herr-seppia commented on governance-core/src/gql.rs
> +}
I believe that, in this specific case, it doesn't help the readability.

Do we have this formatting guide written somewhere? If no, I would like to skip it for now

2023-03-10 09:38 UTC, Daksh14 commented on governance-core/src/gql.rs
> +}
The language does not impose a fixed set of guidelines but it helps to have a consistent one on board to support readability. It can get messy without one.

2023-03-10 09:41 UTC, Daksh14 approved these changes
🥶LGTM

2023-03-10 10:02 UTC, merged